### ISSUE TITLE
Extend available countries ( shipping worldwide )

### ISSUE THREAD

**Issue by drupalranger** [mvgucht/drupal-commerce_dpd#8]
Hi, I've got a question about availability of "Ship to" countries handled by this module.
In code I've found 
function `commerce_dpd_country_get_list()` function, which provides limited list of countries handled by shipping services: 
https://github.com/mvgucht/drupal-commerce_dpd/blob/master/commerce_dpd/commerce_dpd.module#L1025

As I see this list limits "Ship to" option in shipping method. 
My question is, what will happen if I will modify this function, to support ALL countries, like this? 

`
function commerce_dpd_country_get_list() {
  include_once DRUPAL_ROOT . '/includes/locale.inc';
  $countries = country_get_list();
  return $countries;
}
`

Is it possible to create DPD orders for non-EU countries like Brazil, United States etc. using this module?

**Comment by mvgucht** [comment]
Hey drupelranger,

I'm not activly maintaining these repos, but as I remember you could add countries to the list here:

https://github.com/mvgucht/drupal-commerce_dpd/blob/d82525e22d7a4672692bec0836d0f3fbd5a88afe/commerce_dpd/commerce_dpd.module#L1035

They are not included from the start because shipping outside of the EU is not a core bussiness of DPD BeNeLux and prices can vary, So please verify the countries you want to add with your local DPD Depot.

Have a nice day.
